@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
left to right direction

package Core{

package Controllers{
class "RegisterTestController" as RTC {
+getClient(TIN)
+getAllTestType()
+getAllParameterCategoriesByTestType(testTypeDto)
+getAllParametersByParameterCategory(listParameterCategoriesDto)
+createTest(listParametersDto, tesTypeDto, listParameterCategoriesDto, TIN, nhsCode)
+saveTest(test)
}
}

package Domain{
class "Company" as C {
-designation
+getClientStore()
+getTestTypeStore()
+getParameterCategoryStore()
+getParametersStore()
+getTestStore()
}

class "Test" as T {
-description
-code
-nhsCode
-collectDateTime
-chemicalAnalysisDateTime
-diagnosisDateTime
-validationDateTime
+Test(tt, parameters, parameterCategories, TIN, nhsCode)
+generateCode()
+updateTestStatus()
}
}

package Stores{
class "ClientStore" as CS {
+getClient(TIN)
}

class "TestTypeStore" as TTS {
+getAllTestType()
}

class "TestStore" as TS {
createTest (tt, parameters, parameterCategories, TIN, nhsCode)
+saveTest(test)
+hasTest(test)
+addTest(test)
}

class "ParametersStore" as PS {
getAllParametersByParameterCategory(listParameterCategoriesDto)
}

class "ParameterCategoryStore" as PCS {
+getAllParameterCategoriesByTestType(testTypeDto)
}
}

package Mappers{
class "ClientMapper" as CM {
+toDto(cl)
}

class "TestTypeMapper" as TTM {
+toDto(listTestType)
+toModel(testTypeDto)
}

class "ParametersMapper" as PM {
+toDto(listParameters)
+toModel(listParametersDto)
}

class "ParameterCategoryMapper" as PCM {
+toDto(listParameterCategories)
+toModel(listParameterCategoriesDto)
}
}
}

package UI{
class "RegisterTestUI" as RTUI
}

RTUI ..> RTC
RTC ..> CS
RTC ..> CM
RTC ..> C
RTC ..> TTS
RTC ..> TTM
RTC ..> PCS
RTC ..> PCM
RTC ..> PS
RTC ..> PM
RTC ..> TS
TS ..> T

@enduml