@startuml
autonumber

actor "Laboratory Coordinator" as labC
activate labC

labC -> System ++: import tests from a .csv file
System --> labC --: requests file path
labC -> System ++: inserts file path
activate System
loop for each test present on the file
System -->  labC : display the test being imported
end
System --> labC : informs about the import success


@enduml