@startuml
skinparam classAttributeIconSize 0
left to right direction

package "Core"{

package "DTO"{

class "ParameterCategoryDto" as pcDto{
+toDto(List<ParameterCategory> parameterCategory)
}

}

package "Controllers"{

class "CreateParameterCategoryController" as CPCC {
+CreateParameterCategoryController()
+getAllParameterCategoriesDto()
+createParameterCategory(name, code)
+saveParameterCategory()
+getParameterCategoryByCode(code)
+getAllParameterCategories()
}

}

package "Stores"{

class "ParameterCategoryStore" as PCS {
+ParameterCategoryStore()
+createParameterCategory(name, code)
+saveParameterCategory(pc)
+validateParameterCategory(pc)
+addParameterCategory(pc)
+getParameterCategoryByCode(code)
+getAllParameterCategories()
}

}

package "Domain"{
class "Company" as COMP {
-designation
+getParameterCategoryStore()
}

class "ParameterCategory" as PC {
-name
-code
+ParameterCategory(name, code)
}

}

}

package "UI"{
class "CreateParameterCategoryUI" as CPCUI
}


CPCUI ..> CPCC
COMP ..> PCS
PCS ..> PC  :creates
CPCC ..> PC
CPCC ..> COMP
CPCC ..> pcDto
COMP "1" --> "*" PC : adopts

@enduml