@startuml
skinparam classAttributeIconSize 0


class ParameterStore{
  +boolean createParameter(code, designation, description, pcat)
  +boolean saveParameter(parameter)
  -boolean validate(parameter)
  -boolean add(parameter)
  +List <Parameter> getAllParameters()
}

class ParameterCategoryStore{
  +List <ParameterCategory> getAllParameterCategories()
}


class Parameter {
  - String designation
  - String description
  - String code
  +Parameter(code,description,designation,pcat)
}

class Company {
  -designation
  +getParameterCategoryStore()
  +String getParameterCategoryById(categoryId)
  +getParameterStore()
}

class ParameterCategory {
  -String code
  -String description
  -String nhsID
}



class ParamCatMapper{
  +toDto(lpc)
}


class CreateParameterController {
  +getAllParameterCategories()
  +toDto(lpc)
  +boolean createParameter(code,designation,description,categoryId)
  +boolean saveParameter()
}

class CreateParameterUI {
}

CreateParameterUI ..> CreateParameterController
CreateParameterController ..> ParameterCategory
CreateParameterController ..> ParamCatMapper
CreateParameterController ..> Parameter
CreateParameterController ..> Company
Company ..> ParameterStore
Company ..> ParameterCategoryStore

Company "1" -- "*" Parameter : > capable of analysing
Company "1" -- "*" ParameterCategory : > adopts
ParameterCategory "1" -- "*" Parameter : < presented under



@enduml