@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
class Company
class Administrator
class ParameterCategory
class Parameter


Company "1" -- "*" Parameter : > capable of analysing
Company "1" -- "*" ParameterCategory : > adopts
Company "1" -- "*" Administrator : > knows
ParameterCategory "1" -- "*" Parameter : < presented under
Administrator "*" -- "*" ParameterCategory : < created by

skinparam classAttributeIconSize 0
class Company{
-designation
}



class ParameterCategory{
-code
-description
-nhsID
}

class Parameter{
-designation
-description
-code
}

class Administrator{
}


@enduml