@startuml
skinparam classAttributeIconSize 0


class ParameterStore{
  +Parameter createParameter(code, designation, description, pcat)
  +boolean saveParameter(parameter)
  -boolean validate(parameter)
  -boolean add(parameter)
  +List <Parameter> getAllParameters()
}

class ParameterCategoryStore{
  +List <ParameterCategory> getAllParameterCategories()
  +ParameterCategory getParameterCategoryByCode(code)
}


class Parameter {
  - String designation
  - String description
  - String code
  +Parameter(code,description,designation,pcat)
}

class Company {
  -String designation
  +getParameterCategoryStore()
  +getParameterStore()
}

class ParameterCategory {
  -String name
  -String code
  +ParameterCategory(name, code)
}



class ParameterCategoryMapper{
  +List<ParameterCategoryDto> toDto(lpc)
}


class CreateParameterController {
  +CreateParameterController()
  +List<ParameterCategoryDto> toDto()
  +ParameterCategory getParameterCategoryByCode(code)
  +boolean createParameter(code,designation,description,code)
  +boolean saveParameter()
  +List<Parameter> getAllParameters()
}

class CreateParameterUI {
}

CreateParameterUI ..> CreateParameterController
CreateParameterController ..> ParameterCategory
CreateParameterController ..> ParameterCategoryMapper
CreateParameterController ..> Parameter
CreateParameterController ..> Company
Company ..> ParameterStore
Company ..> ParameterCategoryStore

Company "1" -- "*" Parameter : > capable of analysing
Company "1" -- "*" ParameterCategory : > adopts
ParameterCategory "1" -- "*" Parameter : < presented under



@enduml