@startuml
'https://plantuml.com/class-diagram
hide methods
left to right direction
class Administrator
class ParameterCategory
class Parameter
class Company

Administrator "1" -- "*" ParameterCategory : < created by
ParameterCategory "1" -- "*" Parameter : < presented under
Company "1" -- "*" Parameter : > capable of analysing

skinparam classAttributeIconSize 0

class Administrator{
}

class ParameterCategory{
-code
-description
-nhsID
}

class Parameter{
-designation
-description
-code
}

class Company{
-designation
}

@enduml