@startuml
autonumber


actor "Administrator" as ADMIN

participant ":System" as SYST

activate ADMIN
ADMIN -> SYST : Starts the proccess of registering a new clinical analysis laboratory
activate SYST

loop
SYST --> ADMIN : Shows list with test types and asks to select the ones the lab operates
deactivate SYST
ADMIN -> SYST : Selects corresponding test type
activate SYST
end 

SYST --> ADMIN : Requests data (i.e., labID) 
deactivate SYST

ADMIN -> SYST : Types requested data
activate SYST
SYST --> ADMIN : Shows requested data and asks for confirmation
deactivate SYST

ADMIN -> SYST : Confirms the data
activate SYST


SYST --> ADMIN : Informs the success of the operation
deactivate SYST

deactivate ADMIN

@enduml