@startuml
skinparam classAttributeIconSize 0

class "Test"
class "Client"
class "Company"

"Company" "1" - "*" "Test" : > performs
"Client" "1" - "*" "Test" : < requested by
"LaboratoryCoordinator" "1..*" - "*" "Employee" : < is a
"Employee" "*" - "1" "Company" : > works for

@enduml