@startuml
skinparam classAttributeIconSize 0
left to right direction

package Core{

package Domain{
class "Company" as C {
-String designation
+getTestStore()
}

class "ParameterCategory" as PC{
-String name
-String code
+ParameterCategory(name, code)
}

class "TestType" as TT {
-String code
-String description
-String collectingMethod
-ParameterCategory parameterCategory
-List <ParameterCategory> parameterCategoriesList
+TestType(code, description, collectingMethod, parameterCategory)
+TestType(code, description, collectingMethod, parameterCategoriesList)
}

}



package Stores{
class "TestStore" as TS{
-List<Test> testList
+List <Test> getAllTests()
+boolean validateTest()
}
}



package Controllers{
class "ValidateTestController" as VTC {
+ValidateTestController()
+List<TestDto> getAllTestsDto()
+boolean validateTest()
}





}

package Mappers{
class "TestTypeMapper" as ttM{
+List <TestTypeDto> toDto(List<TestType>)
}

class "ParameterCategoryMapper" as pcM{
+List <ParameterCategoryDto> toDto(List<ParameterCategory>)
}

}


package Dto{
class "TestTypeDto" as ttDto{
}

class "ParameterCategoryDto" as pcDto{
}

}

}
package UI{
class "ValidateTestUI" as VTUI
}

VTUI ..> VTC

C ..> TS
VTC ..> C
VTC ..> ttM
VTC ..> ttDto
TT "*" -- "1" PC : > analyzes a
TS ..> TT
ttM ..> ttDto
pcM ..> pcDto


C "1" -- "*" TT : > adopts
C "1" -- "*" PC : > adopts

@enduml