@startuml
skinparam classAttributeIconSize 0
left to right direction

class "Company" as C {
-designation
}

class "categoriesNameMapper" as cNM {
+toDTO(listCategoriesName)
}

class "TestTypeStore" as TTS{
+create(code, description, collectingMethod)
+validate(tt)
+add(tt)
+getAllTestTypes()
}

class "ParameterCategoryStore" as PCS{
+getAllParameterCategories()
}

class "TestType" as TT {
-code
-description
-collectingMethod
-ParameterCategory
+TestType(code, description, collectingMethod, ParameterCategory)
}

class "CreateTestTypeController" as CTTC {
+createTestType(code, description, collectingMethod)
+validateTestType()
+saveTestType()
}

class "CreateTestTypeUI" as CTTUI
class "TestType" as TT
class "CreateTestTypeController" as CTTC

CTTUI ..> CTTC

C ..> PCS

TTS ..> C

CTTC ..> TT
CTTC ..> C
CTTC ..> cNM

C "1" --> "*" TT : adopts

@enduml