@startuml
skinparam classAttributeIconSize 0
left to right direction

class "Company" as C {
-String designation
+getTestTypeStore()
+getParameterCategoryStore()
}

class "categoriesNameMapper" as cNM {
+List <ParameterCategory> toDTO(listCategoriesName)
}

class "TestTypeStore" as TTS{
+boolean create(code, description, collectingMethod)
+boolean validate(tt)
+bollean add(tt)
+List <TestType> getAllTestTypes()
}

class "ParameterCategoryStore" as PCS{
+List <ParameterCategory> getAllParameterCategories()
}

class "TestType" as TT {
-String code
-String description
-String collectingMethod
-List <ParameterCategory> ParameterCategories
+TestType(code, description, collectingMethod, ParameterCategories)
}

class "CreateTestTypeController" as CTTC {
+boolean createTestType(code, description, collectingMethod)
+boolean validateTestType()
+boolean saveTestType()
}

class "Test" as T{
-String code
-String description
-String collectingMethod
}

class "ParameterCategory" as PC{
-String code
-String description
-String nhsID
}

class "CreateTestTypeUI" as CTTUI
class "TestType" as TT
class "CreateTestTypeController" as CTTC
class "Administrator" as admin

CTTUI ..> CTTC

C ..> PCS

TTS ..> C

CTTC ..> TT
CTTC ..> C
CTTC ..> cNM


TT "1" -- "*" T: < is of
TT "*" -- "1" PC : > analyzes a

C "1" -- "*" TT : > adopts
C "1" -- "*" PC : > adopts

admin "*" -- "*" PC : < created by

admin "*" -- "*" TT : < created by


@enduml