@startuml
skinparam classAttributeIconSize 0
left to right direction

class "Company" as C {
-designation
}

class "TestTypeStore" as TTS{
+createTestType(code, description, collectingMethod)
+validateTestType(tt)
+addTestType(tt)
}

class "ParameterCategoryStore" as PCS{
+getParameterCategoryByCode(code)
+getDesignation()
}

class "TestType" as TT {
-code
-description
-collectingMethod
+TestType(code, description, collectingMethod)
}

class "CreateTestTypeController" as CTTC {
+createTestType(code, description, collectingMethod)
+saveTestType()
}

class "CreateTestTypeUI" as CTTUI
class "TestType" as TT
class "CreateTestTypeController" as CTTC

CTTUI ..> CTTC
C ..> PCS
TTS ..> C
CTTC ..> TT
CTTC ..> C
C "1" --> "*" TT : adopts

@enduml