@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor MedicalLabTechnician as MLT

activate MLT
MLT -> System ++: requests to see the tests with samples to be collected
System --> MLT --: shows the tests and asks to select one
MLT -> System ++: selects one test
System --> MLT --: requests data (number of samples to be collected)
MLT -> System ++: types requested data
System --> MLT --: shows the data and requests a confirmation
MLT -> System ++: confirms the data
System --> MLT --: generates the sample barcode and informs operation success

deactivate MLT
@enduml