@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as A
activate A


A -> ":SendReportUI" : send the covid-19 report to the NHS
activate ":SendReportUI"
":SendReportUI" --> A: define the date to see the report, the interval of dates, the number of historical day points, \n select between a simple linear and multilinear regression model and define the significance level
deactivate ":SendReportUI"

A -> ":SendReportUI" : types and selects the requested data
activate ":SendReportUI"
":SendReportUI" -> ":SendReportController": getAllTestWithResultCovidPositive()

activate ":SendReportController"
":SendReportController" -> ":Company" : store = getTestStore()
activate ":Company"
deactivate ":Company"

":SendReportController" -> ":store: TestStore" : listTestWithResultCovidPositive = getAllTestWithResultCovidPositive()
activate ":store: TestStore"
deactivate ":store: TestStore"

deactivate ":SendReportController"

":SendReportUI" -> ":SendReportController" : generateNHSReport(listTestWithResultCovidPositive)
activate ":SendReportController"

":SendReportController" -> ":Company" : report = generateNHSReport(listTestWithResultCovidPositive)
activate ":Company"

create "report : NHSReport"
":Company" --> "report : NHSReport" : create(listTestWithResultCovidPositive)

deactivate ":Company"

":SendReportController" -> "report : NHSReport": data = calculateData()
activate "report : NHSReport"
deactivate "report : NHSReport"

":SendReportController" -> "Report2NHS": writeUsingFileWriter (data)

activate "Report2NHS"

deactivate "Report2NHS"

deactivate ":SendReportController"

":SendReportUI" --> A: show the generated report and request a confirmation
deactivate ":SendReportUI"

A -> ":SendReportUI": confirms the data
activate ":SendReportUI"

":SendReportUI" -> ":SendReportController": saveNHSReport(nhsReport)

activate ":SendReportController"

":SendReportController" -> "report : NHSReport" : validateNHSReport()
activate "report : NHSReport"
deactivate "report : NHSReport"

deactivate ":SendReportController"


":SendReportUI" --> A: informs operation success
deactivate ":SendReportUI"

@enduml