@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Receptionist" as R
activate R
R -> System ++: register a test to be performed to a registered client
System -->  R --: request data (TIN)
R -> System ++: types requested data
System -->  R --: shows the client's information and request a confirmation
R -> System ++: confirms the data
System --> R --: shows the test types and ask to select one
R -> System ++: selects the test type
System --> R --: show all parameter categories according to the test type and ask to select one or more
R -> System ++: selects the parameter category(ies)
System --> R --: show all parameters according to the parameter category(ies) and ask to select one or more
R -> System ++: selects the parameter(s) to be analysed
System --> R --: show all data and request a confirmation
R -> System ++: confirms the data
System --> R --: register test and informs operation success
@enduml